server:
  port: 8080
  servlet:
    context-path: /moontruyen

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/moontruyen"
    username: root
    password: moontruyen
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true