server:
  port: 8080
  servlet:
    context-path: /moontruyen


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/moontruyen"

    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true